services:
  tor:
    image: tor:alpine
    container_name: tor
    networks:
      - tor_net
    volumes:
      - tor_uds:/var/run/tor/
      - ./tor/torrc:/etc/tor/torrc:ro
      - tor_data:/var/lib/tor/
    read_only: true
    cap_drop:
      - ALL
    restart: unless-stopped

  proxy:
    image: nginx:alpine
    container_name: proxy
    networks:
      - app_net
    volumes:
      - tor_uds:/var/run/tor/
      - ./nginx/proxy_seguro.conf:/etc/nginx/nginx.conf:ro
      - nginx_run:/var/run/
      - nginx_cache:/var/cache/nginx/
    read_only: true
    cap_drop:
      - ALL
    restart: unless-stopped

networks:
  tor_net:
    internal: false
  app_net:
    internal: true

volumes:
  tor_uds:
  tor_data:
  nginx_run:
  nginx_cache:
