worker_processes auto;
pid /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    # Disable emitting Nginx version on error pages and in the "Server" response header field.
    server_tokens off;

    # Timeouts to mitigate Slowloris and resource exhaustion
    client_body_timeout 10s;
    client_header_timeout 10s;
    keepalive_timeout 5s;
    send_timeout 10s;

    server {
        # Listen on Unix Domain Socket as requested
        listen unix:/var/run/sicbox/nginx.sock;

        # Strip Server and X-Powered-By
        proxy_hide_header X-Powered-By;
        proxy_hide_header Server;
        add_header Server "" always;

        # Rewrite Origin IP for backend
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP 127.0.0.1;
        proxy_set_header X-Forwarded-For 127.0.0.1;

        location / {
            proxy_pass http://unix:/var/run/sicbox/sicbox.sock;

            # Sanitization headers again just in case
            proxy_hide_header X-Powered-By;
            proxy_hide_header Server;
        }
    }
}
